sudo: required
services:
  - docker

before_install:
  - docker build -t aurerelily/react-test -f .client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aurerelily/react-test npm test -- --coverage

after_success:
  - docker build -t aurerelily/multi-client ./client
  - docker build -t aurerelily/multi-nginx ./nginx
  - docker build -t aurerelily/multi-server ./server
  - docker build -t aurerelily/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push aurerelily/multi-client
  - docker push aurerelily/multi-nginx
  - docker push aurerelily/multi-server
  - docker push aurerelily/multi-worker